services:
  surakshya-backend:
    image: surakshya-back-image
    container_name: surak-back-con
    build: .
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql
    container_name: mysql-con
    ports:
      - 3306:3306
    env_file: .sqlenv
    volumes:
      - sql_data:/var/lib/mysql
    restart: always

volumes:
  sql_data: